name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Update from upstream
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "CI Bot"
          git config --global user.email "noreply@example.com"
          git remote add upstream https://github.com/blender/blender.git
          git fetch upstream
          git merge upstream/master
      - name: Generate diff
        run: |
          cd $GITHUB_WORKSPACE
          git diff upstream/master master > $HOME/blender_ply.diff
      - name: Upload diff as artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff
          path: /home/runner/blender_ply.diff
      - name: Make release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Cleaned Release"
          files: |
            /home/runner/blender_ply.diff